# coding: utf-8

desc 'Build site'
task :build do
  system("jekyll build")
end

desc 'Preview on local machine'
task :serve do
  system("jekyll serve")
end

desc 'Clean up files generated by jekyll build'
task :clean do
  require 'fileutils'
  FileUtils.rm_rf('_site')
end

task :default => :build
