# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "collins_notify"
  s.version = File.read 'VERSION'

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Blake Matheny"]
  s.date = "2013-01-31"
  s.description = "Send notifications via hipchat, IRC and email"
  s.email = "bmatheny@tumblr.com"
  s.executables = ["collins-notify"]
  s.files = [
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/collins-notify",
    "collins_notify.gemspec",
    "lib/collins_notify.rb",
    "lib/collins_notify/adapter/email.rb",
    "lib/collins_notify/adapter/helper/carried-pigeon.rb",
    "lib/collins_notify/adapter/hipchat.rb",
    "lib/collins_notify/adapter/irc.rb",
    "lib/collins_notify/application.rb",
    "lib/collins_notify/command_runner.rb",
    "lib/collins_notify/configuration.rb",
    "lib/collins_notify/configuration_mixin.rb",
    "lib/collins_notify/errors.rb",
    "lib/collins_notify/notifier.rb",
    "lib/collins_notify/options.rb",
    "lib/collins_notify/version.rb",
    "sample_config.yaml",
    "templates/default_email.erb",
    "templates/default_email.html.erb",
    "templates/default_hipchat.erb",
    "templates/default_irc.erb"
  ]
  s.homepage = "https://github.com/tumblr/collins/tree/master/support/ruby/collins-notify"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Notifications for Collins"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<addressable>, ["~> 2.3.2"])
      s.add_runtime_dependency(%q<collins_client>, ["~> 0.2.10"])
      s.add_runtime_dependency(%q<hipchat>, ["~> 0.7.0"])
      s.add_runtime_dependency(%q<mail>, ["~> 2.4.4"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<addressable>, ["~> 2.3.2"])
      s.add_dependency(%q<collins_client>, ["~> 0.2.10"])
      s.add_dependency(%q<hipchat>, ["~> 0.7.0"])
      s.add_dependency(%q<mail>, ["~> 2.4.4"])
      s.add_dependency(%q<nokogiri>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<addressable>, ["~> 2.3.2"])
    s.add_dependency(%q<collins_client>, ["~> 0.2.10"])
    s.add_dependency(%q<hipchat>, ["~> 0.7.0"])
    s.add_dependency(%q<mail>, ["~> 2.4.4"])
    s.add_dependency(%q<nokogiri>, ["~> 1.5.2"])
  end
end

