source 'https://rubygems.org'

gem 'addressable',    '~> 2.3.2'
gem 'collins_client', '~> 0.2.10'
gem 'hipchat',        '~> 0.7.0'
gem 'mail',           '~> 2.4.4'
gem 'nokogiri',       '~> 1.5.2'

group :development do
  gem 'i18n',         '< 0.7.0'	# versions above 0.7.0 require ruby 1.9.3
  gem "rspec", "~> 2.12.0"
  gem "yard", "~> 0.8.3"
  gem "rdoc", "~> 3.12"
  gem "bundler", ">= 1.2.0"
  gem "jeweler", "~> 1.8.4"
  gem "simplecov"
end
