#!/usr/bin/env ruby

require "rubygems"
require "bundler/setup"

require "thrift"
require "thrift_client"
require "indefatigable_service"
require "irb"

class IndefatigableClient < ThriftClient
  DEFAULTS = { :transport_wrapper => Thrift::FramedTransport }
  def initialize(servers = nil, options = {})
    if servers.nil? or servers.empty?
      STDERR.puts "No servers specified, using 127.0.0.1:9999"
      servers = ['127.0.0.1:9999']
    else
      servers = Array(servers)
    end

    super(Ira::IraService::Client, servers, DEFAULTS.merge(options))
  end
end

puts "Hint: the client is in the variable `$client`"
$client = IraClient.new ARGV.shift

IRB.start
