source :rubygems

Encoding.default_external = Encoding::UTF_8
gem 'collins_client', '~> 0.2.9'
gem 'escape',         '~> 0.0.4'

group :development do
  gem "rspec", "~> 2.10.0"
  gem "yard", "~> 0.8"
  gem 'redcarpet'
  gem 'webmock'
  gem "bundler", "~> 1.2.1"
  gem "jeweler", "~> 1.8.4"
  gem 'simplecov'
end
