source 'https://rubygems.org'

Encoding.default_external = Encoding::UTF_8
gem 'collins_client'
gem 'escape'

group :development do
  gem 'rspec', '~> 2.99'
  gem 'yard'
  gem 'redcarpet'
  gem 'webmock'
  gem "jeweler", "~> 1.8.4"
  gem 'bundler'
  gem 'simplecov'
  gem 'rake'
end
